green-action/green-action

app/mypage/page.tsx
utils/date/date.ts

```
+ 날짜 string 변환 함수 새로 추가했어요! (시간없이 날짜만 뜨도록 하는 함수)
```
```
```
```
|기능|스크린샷|
```

[feat] 마이페이지 북마크리스트까지 조회 완료, 프로필 수정 기능 중

---

app/_api/community/community-api.ts
app/_api/individualAction-add/add-api.ts
app/_components/community/AddPostModal.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/community/CommunityListPost.tsx
app/_types/community/community.ts
app/community/page.tsx
app/individualAction/add/page.tsx

closed #13 
- 커뮤니티 글쓰기 등록 로직
- 이미지 스토리지에 업로드
- url 반환받아 formData에 추가
- formData 테이블에 insert
- 커뮤니티 리스트 query키 무효화
```ts
// AddPostModal.tsx
// post등록 후 communityList 쿼리키 무효화할 mutation
const { mutate: insertFormDataMutation } = useMutation({
mutationFn: async ({ formData, currentUserUId }: CommunityPostMutation) => {
const post_id = await insertCommunityPostFormData({
formData,
currentUserUId,
});
return post_id;
},
onSuccess: () => {
queryClient.invalidateQueries({ queryKey: [QUERY_KEY_COMMUNITYLIST] });
},
});
// '작성완료' 클릭시
const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
event.preventDefault();
const formData = new FormData(event.currentTarget);
// 드롭다운에서 선택한 값을 formData에 추가
formData.append("action_type", Array.from(selectedKeys).join(", "));
try {
// 확인창 표시 …
```

[feat] 커뮤니티 리스트 조회, 글쓰기 등록

---

app/_api/community/community-api.ts
app/_api/queryKeys.ts
app/_components/community/Comment.tsx
app/_components/community/CommunityDetailModal.tsx
app/_types/community/community.ts

#24 
- 댓글 리스트 조회
```ts
// post_id로 상세모달창 댓글리스트 가져오기
export const getCommunityCommentsList = async (post_id: string) => {
try {
const { data, error } = await supabase
.from("community_comments")
.select()
.eq("post_id", post_id);
if (error) {
throw error;
}
return data;
} catch (error) {
console.error("Error inserting data:", error);
throw error;
}
};
```
- 댓글 등록
```ts
// 댓글 insert
export const insertCommunityComment = async ({
content,
currentUserUid,
post_id,
}: InsertComment) => {
try {
const { error } = await supabase
.from("community_comments")
.insert([{ content, post_id, user_uid: currentUserUid }]);
if (error) {
throw error;
}
} catch (error) {
console.error("Error inserting comment:", error);
throw error;
}
};
```

[feat] 커뮤니티 게시글 상세 모달창 - 댓글 조회, 등록

---

app/_api/community/comments-api.ts
app/_api/community/community-api.ts
app/_api/individualAction-add/add-api.ts
app/_components/community/AddPostModal.tsx
app/_components/community/Comment.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/community/CommunityListPost.tsx
app/_types/community/community.ts
app/individualAction/add/page.tsx

[refactor] 작성자 정보 보여주기 (커뮤니티 리스트, 상세 모달창, 댓글)

---

app/community/edit/[id]/page.tsx

[chore] merge dev

---

app/_api/bookmark/bookmarkQueries.ts
app/_components/bookmark/Bookmark.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/community/CommunityListPost.tsx
app/_components/groupAction/GroupModal.tsx
app/_components/likes/Likes.tsx
app/_hooks/useQueries/bookmarks/index.ts
app/groupAction/page.tsx

[add] - 좋아요 기능 완료

---

app/_api/bookmark/bookmarkQueries.ts
app/_components/bookmark/Bookmark.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/likes/Likes.tsx

[add] - bookmark/likes 삭제기준 바꿈

---

app/_api/community/comments-api.ts
app/_api/community/community-api.ts
app/_api/individualAction-add/add-api.ts
app/_api/queryKeys.ts
app/_components/community/AddPostModal.tsx
app/_components/community/Comment.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/community/CommunityListPost.tsx
app/_components/community/EditPostModal.tsx
app/_components/individualAction/PageTap.tsx
app/_types/community/community.ts
app/individualAction/add/page.tsx
app/individualAction/page.tsx

[feat] 로그인 유저정보 useSession 리팩토링 외 다수

---

app/_api/community/comments-api.ts
app/_api/goods/goods_api.ts
app/_components/community/Comment.tsx
app/_components/goods/Goods.tsx
app/_components/goods/ProductInfoModal.tsx
utils/supabase/type/supabase.d.ts

goods 로그인한 유저 id useSession으로 변경 후 point mutation이 안되는 문제 발생,, 해결,,
community 댓글 수정 삭제 기능 구현
수정 시 댓글 순서 변경됨 (이후 해결해야 할 일)
```
```
```
|기능|스크린샷|
```

[feat] 굿즈 유저id session으로 변경, 커뮤니티 댓글 수정/삭제

---

app/_api/bookmark/bookmarkQueries.ts
app/_api/mypage/mypage-list-api.ts
app/_components/bookmark/Bookmark.tsx
app/_components/community/CommunityListPost.tsx
app/_components/layout/Header.tsx
app/_components/main/MainSlider.tsx
app/_components/mypage/MyActionCard.tsx
app/_components/mypage/RecruitSelectTab.tsx
app/_hooks/useMutations/mypage/index.ts
app/community/page.tsx
app/mypage/page.tsx
app/page.tsx
package.json
yarn.lock

+ 헤더에서 하위탭 선택 후 다른 탭 으로 이동 시에 탭선택이 바뀌지 않는 문제 해결중
+ 여전히 유저uid 관련해 마이페이지 데이터 조회안되는 문제. (임시 uid 사용해 마이페이지 구현 중)
+ 마이페이지에서 찜 기능 활용 시 바로 렌더링 안되는 문제 등 수정 예정
```
```
```
|기능|스크린샷|
```

[feat/fix]  메인페이지 슬라이더, 마이페이지 action 삭제 기능 및 모집상태별분류 버그 해결

---

app/_api/individualAction-detail/detail-api.ts
app/_components/goods/Goods.tsx
app/_components/kakaoShare/KakaoShare.tsx
app/individualAction/detail/[id]/page.tsx
package-lock.json
package.json
yarn.lock

```
```
```
```
```
|기능|스크린샷|
```

[design] 개인액션 상세페이지 ui

---

app/_api/community/community-api.ts
app/_components/community/AddComment.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/individualAction-add/FirstInputBox.tsx
app/_components/individualAction-add/SecondInputBox.tsx
app/_components/individualAction-add/ThirdInputBox.tsx
app/_hooks/useMutations/comments/index.ts
app/_hooks/useMutations/community/index.ts
app/_hooks/useQueries/comments/index.ts
app/_hooks/useQueries/community/index.ts
app/_types/comments/comments.ts
app/community/page.tsx
app/individualAction/add/page.tsx
yarn.lock

[feat] 커뮤니티 리스트 정렬(최신순, 좋아요순), 댓글리스트 정렬(최신순)

---

app/_components/goods/Goods.tsx
app/_components/goods/ProductInfoModal.tsx
app/_components/kakaoShare/KakaoShare.tsx
app/individualAction/detail/[id]/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[feat/design] 상세페이지 북마크, 참여하기, goods 페이지 ui

---

middleware.ts
yarn.lock

#55 
```
import { updateSession } from "@/utils/supabase/middleware";
import { getSession } from "next-auth/react";
import { type NextRequest } from "next/server";
export async function middleware(request: NextRequest) {
const session = await getSession();
console.log("-----------------");
console.log(session);
console.log("-----------------");
// 로그인이 필요한 페이지 리스트
const LOGIN_REQUIRED_PAGES = [
`/mypage`,
`/community`,
`/individualAction`,
`/goods`,
];
const LOGIN_NOT_REQUIRED_PAGES = [`/login`, `/signup`];
// 로그인이 필요한 페이지 리스트
LOGIN_REQUIRED_PAGES.forEach((page) => {
if (request.nextUrl.pathname === page) {
if (!session) {
return {
status: 302,
headers: {
location: `/login`,
},
};
}
}
});
LOGIN_NOT_REQUIRED_PAGES.forEach((page) => {
if (request.nextUrl.pathname === page) {
if (session) { …
```

[add] - middiware

---

app/_api/bookmark/bookmarkQueries.ts
app/_api/main/main-api.ts
app/_api/mypage/mypage-profile-api.ts
app/_api/queryKeys.ts
app/_components/bookmark/Bookmark.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/community/CommunityListPost.tsx
app/_components/community/EditPostModal.tsx
app/_components/customConfirm/CustomConfirm.tsx
app/_components/layout/Header.tsx
app/_components/likes/Likes.tsx
app/_components/main/MainSlider.tsx
app/_components/mypage/MyActionCard.tsx
app/_components/mypage/MyProfile.tsx
app/_components/mypage/ProfileImgUpload.tsx
app/_hooks/useMutations/bookmarks/index.ts
app/_hooks/useMutations/mypage/index.ts
app/_hooks/useQueries/mypage/index.ts
app/_types/community/community.ts
app/_types/mypage/mypage.ts
app/mypage/page.tsx
app/page.tsx

closed #50, #51, #52
```
```
```
```
```
|기능|스크린샷|
```

[fix] 북마크 한꺼번에 해제되는 문제, 메인/마이페이지 글 수정 및 북마크수정 시 렌더링 문제 해결, custom confirm 창 활용 등

---

app/_components/bookmark/Bookmark.tsx

```
```
```
```
```
|기능|스크린샷|
```

[add] 임시 유저 uid 삭제

---

app/_components/goods/ProductInfoModal.tsx

```
```
```
```
```
|기능|스크린샷|
```

[feat] goods 페이지 상세버튼 로딩중 해결

---

app/_components/bookmark/Bookmark.tsx
app/_components/customConfirm/CustomConfirm.tsx
app/_components/likes/Likes.tsx
utils/debounce/debounce.ts
yarn.lock

```
"use client";
import { useAddLike, useRemoveLike } from "@/app/_hooks/useMutations/bookmarks";
import { useFilterLikes } from "@/app/_hooks/useQueries/bookmarks";
import { debounce } from "@/utils/debounce/debounce";
import { CircularProgress } from "@nextui-org/react";
import { useSession } from "next-auth/react";
import { useCallback } from "react";
import { CiHeart } from "react-icons/ci";
import { FaHeart } from "react-icons/fa";
const Likes = ({ post_id }: { post_id: string }) => {
const { data, isLoading } = useFilterLikes(post_id);
const addLikeMutation = useAddLike();
const removeLikeMutation = useRemoveLike();
const session = useSession();
const user_uid = session.data?.user.user_uid as string;
const handleToggle = () => {
const isLiked = data?.likes?.find((like) => …
```

[add] - like debounce 로직 추가

---

app/_api/individualAction-add/add-api.ts
app/_components/community/CommunityDetailModal.tsx
app/_components/community/CommunityListPost.tsx
app/_components/community/PostImgUpload.tsx
app/_components/individualAction-add/ImgUpload.tsx
app/_components/individualAction-edit/ImgEdit.tsx
app/_components/layout/Test.tsx

```tsx
// 드래그 앤 드랍 상태
const [isDragging, setIsDragging] = useState(false);
// 이미지 미리보기 띄우기
const handleShowPreview = (e: React.ChangeEvent<HTMLInputElement>) => {
const file = e.target.files?.[0];
if (!file) {
return;
}
const imageUrl = URL.createObjectURL(file);
setUploadedFileUrls((prev) => [...prev, imageUrl]);
setFiles((prev) => [...prev, file]);
};
// 미리보기 이미지 삭제
const handleDeleteImage = (index: number) => {
setUploadedFileUrls((prev) => {
const updatedUrls = [...prev];
updatedUrls.splice(index, 1);
return updatedUrls;
});
setFiles((prev) => {
const updateFiles = [...prev];
updateFiles.splice(index, 1);
return updateFiles;
});
};
// 드래그 앤 드랍 이벤트 핸들러
const handleDragStart = (e: React.DragEvent<HTMLDivElement>) => {
e.preventDefault();
setIsDragging(true);
};
const handleDragOver = …
```

[feat] 개인액션 생성 페이지 - 이미지 드래그 앤 드롭

---

app/_components/bookmark/Bookmark.tsx
app/_components/layout/Header.tsx
app/_components/main/MainSlider.tsx
app/_components/mypage/MyActionRecruitingModal.tsx
app/_hooks/useMutations/bookmarks/index.ts
app/_hooks/useMutations/mypage/index.ts

closed #64
closed #65
헤더 부모/하위 탭 싱크 맞추고 이동시키기 - 해결한 일부 코드입니다
```
const [parentSelected, setParentSelected] = useState<string>(""); // 부모 탭의 선택 상태
const [childSelected, setChildSelected] = useState<string>(""); // 하위 탭의 선택 상태
const handleSelectedTab = () => {
setParentSelected(pathname);
if (pathname !== "/individualAction" && pathname !== "/groupAction") {
setChildSelected(""); // 해당부모탭 아닌 다른 탭 선택시 하위탭선택 없애기 (초기화)
}
if (pathname === "/groupAction") {
setParentSelected("/individualAction");
setChildSelected("/groupAction");
}
if (pathname === "/individualAction") {
setChildSelected("/individualAction");
}
};
useEffect(() => {
handleSelectedTab();
}, [pathname]);
...
return (
<Tabs
selectedKey={parentSelected} 
...
<div className="flex gap-5 mt-3 px-2 py-0 items-center justify-center w-full …
```

[fix] 헤더 UI 및 마이페이지 렌더링 이슈 해결

---

app/_components/bookmark/Bookmark.tsx
app/_components/customConfirm/CustomConfirm.tsx
app/_components/likes/Likes.tsx
app/api/auth/[...nextauth]/route.ts

없습니다!!
```
"use client";
import { useCallback } from "react";
import {
useAddBookmark,
useRemoveBookmark,
} from "@/app/_hooks/useMutations/bookmarks";
import { useFilterBookmark } from "@/app/_hooks/useQueries/bookmarks";
import { debounce } from "@/utils/debounce/debounce";
import CustomConfirm from "../customConfirm/CustomConfirm";
import { useSession } from "next-auth/react";
import { CircularProgress } from "@nextui-org/react";
import { CiStar } from "react-icons/ci";
import { FaStar } from "react-icons/fa";
const Bookmark = ({
action_id,
mode,
}: {
action_id: string;
mode?: string;
// mode는 없어도 되는 인자
}) => {
const { data: filterBookmark, isLoading } = useFilterBookmark(action_id);
const addBookmarkMutation = useAddBookmark(mode || "");
const removeBookmarkMutation = …
```

[refactor] - debounce 로직 추가

---

app/Provider.tsx
app/_components/bookmark/Bookmark.tsx
app/_components/likes/Likes.tsx
app/layout.tsx
middleware.ts
package.json
yarn.lock

[refactor] - 리팩토링

---

app/_components/mypage/MyProfile.tsx
app/login/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[chore] 이미지 경로 변경

---

app/_components/customConfirm/CustomConfirm.tsx
app/_components/mypage/MyActionCard.tsx
app/test/page.tsx

[design] - customfonfrim 디자인 완료

---

app/_components/bookmark/Bookmark.tsx
app/_components/community/AddPostModal.tsx
app/_components/community/PointModal.tsx

```
"use client";
import { Modal, ModalBody, ModalContent } from "@nextui-org/react";
import Image from "next/image";
import clap from "/app/_assets/image/logo_icon/icon/community/image 50.png";
interface PointModalProps {
isOpen: boolean;
onClose: () => void;
}
const PointModal: React.FC<PointModalProps> = ({ isOpen, onClose }) => {
return (
<>
<Modal placement="center" isOpen={isOpen} onOpenChange={onClose}>
<ModalContent>
{(onClose) => (
<>
<ModalBody className="flex flex-col gap-5 justify-center items-center py-[70px]">
<Image
className="block w-[100px] h-[80px]"
src={clap}
alt="clap"
/>
<p className="font-bold text-center text-[16px]">
축하합니다!
<span className="block">100 Point를 획득하셨습니다!</span>
</p>
<p className="text-[#8f8f8f] text-[12px] text-center">
내용과 관련 없는 이미지일 경우
<br /> 포인트가 …
```

[add] - community 추가하면 포인트모달 창이 나옴

---

app/_components/mypage/MyActionCard.tsx
app/_components/mypage/MyProfile.tsx
app/mypage/page.tsx
middleware.ts

[design] 마이페이지 1020 수정중

---

app/_components/layout/Header.tsx
app/about/page.tsx
app/page.tsx

[refactor] 메인, about 헤더 - root layout 헤더로 변경

---

app/_components/individualAction/PageTap.tsx
app/_components/individualAction/pageList.tsx

```
```
```
```
```
|기능|스크린샷|
```

[design]개인액션리스트 그리드 css 수정

---

app/_components/groupAction/GroupModal.tsx
app/_components/individualAction-add/SecondInputBox.tsx
app/groupAction/page.tsx
yarn.lock

[design] - groupAction style 다시

---

app/api/auth/[...nextauth]/route.ts

```
```
```
```
```
|기능|스크린샷|
```

[fix]소셜로그인 로직수정

---

app/_components/goods/Goods.tsx
app/_components/goods/ProductInfoModal.tsx
app/_components/layout/Header.tsx
app/goods/page.tsx

- 혜나님께 goods 제품 이미지, 페이지 하단 이미지 받으면 추가할 예정
- header.tsx 에만 코드 추가해놨습니다. 메인페이지에서 기능 확인 하실수있어요!
```
```
```
```
```
|기능|스크린샷|
```

[design] goods 페이지 1020 디자인 적용

---

app/_components/bookmark/Bookmark.tsx
app/_components/community/CommunityListPost.tsx
app/_components/customConfirm/CustomConfirm.tsx
app/_components/main/MainSlider.tsx
app/_components/mypage/MyActionCard.tsx

특히 communityListPost 컴포넌트에서, 한 컴포넌트로 여러 페이지에서 써서 인건지 .. 조건부 스타일링을 하고 있는데
수정해서 반영이 되었는데, 또 문제가 생기고 삐져나오고 마진이 안맞고 해서 ㅠㅠ 같은부분을 재차 수정하는 노가다로 ?! 시간이 많이 갔습니다..!
```
```
```
```
```
|기능|스크린샷|
```

[design] laptop 반응형 수정

---

app/_components/goods/Goods.tsx
app/_components/goods/GoodsImg.tsx
app/_components/goods/ProductInfoModal.tsx
app/goods/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[design] goods 페이지 모바일 반응형 디자인

---

app/_api/individualAction-add/add-api.ts
app/_api/messages/groupChat-api.ts
app/_api/messages/privateChat-api.ts
app/_api/queryKeys.ts
app/_components/individualAction/GroupChat.tsx
app/_hooks/useQueries/chats/index.ts
app/_types/realtime-chats/index.ts
app/individualAction/add/page.tsx
app/individualAction/detail/[id]/page.tsx

- 단체 채팅방 클릭시
- 채팅방 id 가져오기
- 이미 채팅 참여중인지 확인
- 새로운 참여인 경우 참가자 테이블에 insert
- 채팅인원 === 모집인원 인 경우 '모집마감'으로 자동 상태변경
```ts
// 단체 채팅방 클릭 핸들러
const handleOpenGroupChatRoom = async () => {
const action_id = params.id;
// 단체 채팅방 room_id 가져오기
const room_id = await getChatRoomId(action_id);
groupRoomIdRef.current = room_id;
// 채팅에 참여중인지 여부 확인(참여중이면 id값 있음, 아직 참여중이 아니면 null)
const participant_id = await checkUserExist({
room_id,
loggedInUserUid: user_uid,
});
// 새로운 참여인 경우 참가자 테이블에 insert
if (!participant_id) {
await insertNewParticipant({
room_id,
loggedInUserUid: user_uid,
});
}
// 채팅 인원 파악, 해당 action의 모집인원
// 채팅인원 === 모집인원 된 경우 -> 모집상태 '모집마감'으로 변경
await countParticipants({
room_id,
action_id,
});
// 채팅방 모달창 open
onGroupChatOpen();
};
```
```ts
import { supabase } from "@/utils/supabase/client";
// …
```

[feat] 단체 채팅방

---

app/_components/community/AddPostModal.tsx
app/_components/community/Comment.tsx
app/_components/community/EditPostModal.tsx
app/_components/customConfirm/CustomConfirm.tsx
app/_components/individualAction-add/FirstInputBox.tsx
app/_components/individualAction-add/ThirdInputBox.tsx
app/individualAction/add/page.tsx
app/individualAction/edit/[id]/page.tsx

[refector] - window.confrim 리팩토링

---

app/_components/bookmark/Bookmark.tsx
app/_components/goods/ProductInfoModal.tsx
app/_components/groupAction/GroupContent.tsx
app/_components/groupAction/GroupSkeleton.tsx
app/_components/likes/Likes.tsx
app/_hooks/useQueries/groupAction/index.ts
app/groupAction/page.tsx

GroupAction ssr페이지로 변경

---

app/_components/chats/PrivateChatRoom.tsx
app/_components/individualAction/ChatButtons.tsx
app/individualAction/detail/[id]/page.tsx

[refactor] 임시 - 참여하기 클릭시 카카오톡 모달창 보여주기

---

app/individualAction/detail/[id]/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[fix] chat buttons props, 모달 관련 이슈 해결

---

app/_components/individualAction-add/FirstInputBox.tsx
app/_components/kakaoMap/SearchMapModal.tsx
app/layout.tsx

api key 하나로 합치기
script 위치 변경 -> 은 상관 없는 거 같고 공식문서에서도 꼭 그렇게 되어있지않으나 일단 시도해봤음
```
```
```
|기능|스크린샷|
```

[fix] 배포 시 카카오맵 api 불러오기 에러 해결 시도

---

app/layout.tsx

```
```
```
```
```
|기능|스크린샷|
```

[chore] Script - beforeInteractive 태그 위치 원래대로

---

app/_components/community/CommunityListPost.tsx
app/_components/kakaoMap/KakaoMap.tsx
app/_components/main/LaptopMainSlidder.tsx
app/_components/main/MainSlider.tsx
app/layout.tsx
app/page.tsx
package.json
tsconfig.json
yarn.lock

```
```
```
```
```
|기능|스크린샷|
```

[design/feat] 카카오맵 라이브러리사용으로 변경, 커스텀오버레이 적용, 디자인 

---

app/_components/community/CommunityListPost.tsx
app/mypage/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[design] 마이페이지 디자인 수정

---

app/mypage/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[fix] css 실수 수정

---

app/signup/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[design] signup 유효성검사 글위치 수정

---

app/mypage/page.tsx
app/signup/page.tsx

Dev signup 유효성검사 오류
```
```
```
```
```
|기능|스크린샷|
```

Dev signup 유효성검사 오류

---

app/_api/constant.ts
app/_components/bookmark/Bookmark.tsx
app/_components/community/AddPostModal.tsx
app/_components/community/CommunityListPost.tsx
app/_components/individualAction/PageList.tsx
app/_components/individualAction/PageTap.tsx
app/_components/kakaoMap/KakaoMap.tsx
app/_components/layout/Header.tsx
app/_components/likes/Likes.tsx
app/_components/mypage/MyActionCard.tsx
app/individualAction/detail/[id]/page.tsx
app/mypage/page.tsx
app/page.tsx

글쓰기 연필아이콘도 디자이너님이 주신걸로 바꿨습니다!
개인액션 리스트 탭 및 상세페이지에서 폰트크기도 조금씩 키웠어요 (desktop,laptop)
그 외에도 디자인 전반적으로 수정했습니다
```
```
```
|기능|스크린샷|
```

[design/refactor] 전반적 디자인 수정 (메인,헤더, action 리스트 및 상세페이지, 북마크좋아요 등)

---

app/_components/chats/HeaderGroupList.tsx
app/_components/chats/HeaderPrivateList.tsx
app/_components/chats/PageChatsList.tsx
app/_components/chats/PagePrivateItem.tsx
app/_types/realtime-chats/index.ts

[refactor] 액션 문의채팅 리스트 - 오전/ 이전 알림 분리, laptop, mobile 디자인

---

app/_components/chats/GroupInsideModal.tsx
app/_components/chats/PrivateChatRoom.tsx

[refactor] 개인채팅방 반응형 리팩토링

---

app/_components/chats/GroupInsideModal.tsx
app/_components/chats/HeaderGroupItem.tsx
app/_components/community/CommunityDetailModal.tsx
app/_components/community/CommunityListPost.tsx
app/_components/community/PostImgEdit.tsx
app/_components/community/PostImgUpload.tsx
app/_components/goods/GoodsImg.tsx
app/_components/groupAction/GroupContent.tsx
app/_components/groupAction/GroupModal.tsx
app/_components/individualAction-add/ImgUpload.tsx
app/_components/individualAction-edit/ImgEdit.tsx
app/_components/individualAction/PageList.tsx
app/_components/mypage/MyActionCard.tsx
app/individualAction/detail/[id]/page.tsx
next.config.js

[refactor] - img 태그 next Image태그로 리팩토링

---

app/_components/community/PostImgUpload.tsx
app/_components/individualAction-add/ImgUpload.tsx
app/individualAction/add/page.tsx

[fix] - 오류해결

---

app/_components/community/AddPostModal.tsx
app/_components/customConfirm/CustomConfirm.tsx
app/_components/individualAction-edit/ImgEdit.tsx
app/_components/individualAction/PageTap.tsx
app/individualAction/detail/[id]/page.tsx

[fix] - Image태그 오류 해결

---

app/_components/groupAction/GroupModal.tsx

[fix] - groupAction image 오류 해결

---

app/_components/community/AddPostModal.tsx
app/_components/individualAction-add/FirstInputBox.tsx
app/_components/individualAction/PageTap.tsx
app/_components/kakaoMap/KakaoMap.tsx
app/_components/kakaoMap/SearchMapModal.tsx
app/_components/kakaoMap/SearchMapResult.tsx
app/_components/layout/Allheader.tsx
app/_components/layout/Mheader.tsx
app/_types/individualAction-add/individualAction-add.ts
app/individualAction/add/page.tsx
app/individualAction/edit/[id]/page.tsx

```
```
```
```
```
|기능|스크린샷|
```

[design] 지도검색모달 모바일 반응형

---

app/_components/about/AboutContent.tsx
app/_components/chats/HeaderGroupItem.tsx
app/_components/chats/HeaderGroupList.tsx
app/_components/chats/HeaderPrivateItem.tsx
app/_components/chats/HeaderPrivateList.tsx
app/_components/chats/PageChatsList.tsx
app/_components/chats/PagePrivateItem.tsx
app/_components/chats/PrivateChatRoom.tsx
app/_components/community/AddComment.tsx
app/_components/goods/ProductInfoModal.tsx
app/_components/layout/Allheader.tsx
app/_components/layout/Chatbot.tsx
app/_components/layout/Header.tsx
app/_components/layout/Mheader.tsx
app/_components/main/LaptopMainSlidder.tsx
app/_components/main/MainSlider.tsx
app/_components/main/MobileSlider.tsx
app/_components/mypage/MyActionCardMobile.tsx
app/_hooks/responsive/index.ts
app/individualAction/edit/[id]/page.tsx
app/mypage/page.tsx
app/page.tsx
components/header/HeaderPage.tsx
next.config.js
yarn.lock

```
```
```
```
```
|기능|스크린샷|
```

[fix] - sroll함수에 debounce적용

---

app/_components/TopButton.tsx
app/_components/layout/Allheader.tsx
app/_components/layout/Mheader.tsx
app/_hooks/responsive/index.ts
components/header/HeaderPage.tsx

[fix] - 마이페이지 로그아웃 문제 해결

---

app/_api/messages/headerPrivateList-api.ts

```
```
```
```
```
|기능|스크린샷|
```

[fix]uid 없을시 null처리

---

app/_components/chats/PrivateChatRoom.tsx
app/_components/layout/Footer.tsx
app/_components/main/MainTextSection.tsx
app/globals.css
app/layout.tsx
package.json
utils/debounce/debounce.ts
yarn.lock

```
yarn
```
or
```
yarn add fontsource-italiana
yarn add @fontsource/inter
yarn add pretendard
```

[refactor] - global.css @font-face import로 변경

---

app/_components/individualAction/PageList.tsx
app/_components/individualAction/PageTap.tsx

```
```
```
```
```
|기능|스크린샷|
```

[design] 개인액션리스트 - 폰트크기 수정

---

app/_components/chats/GroupChatRoom.tsx
app/_components/chats/GroupInsideModal.tsx
app/_components/chats/PrivateChatRoom.tsx

[fix] 채팅방 내부모달창 - 스크롤 영향 이슈 해결
